### ISSUE TITLE
Error "Remote host method get_BufferSize is not implemented" when running on build agent

### ISSUE THREAD

**Issue by juszczukd** [SharpeRAD/Cake.Services#12]
When running automatic build on teamcity agent (runned as service, without console) i got error:

`Executing: & "sc.exe" delete "DocumentFileProcessorService"
Error: System.Management.Automation.RemoteException: Remote host method get_BufferSize is not implemented.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection1 input, PSDataCollection1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection1 input, PSDataCollection1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.RemotePipeline.Invoke(IEnumerable input)
   at Cake.Powershell.PowershellRunner.Invoke(String script, PowershellSettings settings)
   at Cake.Services.ServiceManager.Uninstall(String name, String computer)
   at Submission#0.UninstallService(String name, String computer)
   at Submission#0.UninstallDFPService()
   at Submission#0.PublishDFPServiceToZos()
   at Submission#0.<.ctor>b__512_7()
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Object[] submissionArray, Object& submissionResult)
   at Submission#0.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmission(Func2 submissionRunner)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Cake.Scripting.Roslyn.Nightly.DefaultRoslynNightlyScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()`

Is there a way to pass settings to `Cake.Powershell` as in : 
[method get_BufferSize is not implemented](https://github.com/SharpeRAD/Cake.Powershell/blob/master/TroubleShooting.md#error-message-2) ?

**Comment by SharpeRAD** [comment]
Course 😄, it will be fixed in v0.2.9 👍
